ucsc_genome_browser_setup_script: https://raw.githubusercontent.com/ucscGenomeBrowser/kent/fdded708bc8405da6d0ff43d42f0092a872a0a97/src/product/installer/browserSetup.sh
ucsc_genome_browser_setup_script_checksum: sha256:e47cd21c479a53d3157a4cd54f867dc26420d5f825d0b6954257e3ee3054882d

ucsc_genome_browser_assemblies: ["wuhCor1"]
ucsc_genome_browser_assemblies_env: "OS=linux MACH=x86_64"

ucsc_genome_browser_setting_CGIBINDIR: "/usr/local/apache/cgi-bin/"
# `CGIBINDIR=$APACHEDIR/cgi-bin` is the default value, but this role does not
# perform this kind of variable substitution. Without this setting, hg.conf
# will not be patched.

ucsc_genome_browser_hg_conf_settings:
  # define at least one setting to ensure hg.conf is patched during testing
  login.https: "on"  # the setup script sets this to "off", which breaks hgLogin over https

ucsc_genome_browser_setup_script_path: /usr/local/apache/browserSetup.sh
