---
- name: Ensure UCSC Genome Browser is installed
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Check if UCSC Genome Browser is already installed
      block:
        - name: Stat UCSC Genome Browser installation flag
          ansible.builtin.stat:
            path: "/usr/local/apache/cgiInstallComplete.flag"
          register: ucsc_genome_browser_installation_flag

        - name: Assert UCSC Genome Browser installation flag exists
          ansible.builtin.assert:
            that: ucsc_genome_browser_installation_flag.stat.exists
            fail_msg: "UCSC Genome Browser installation flag not found. Installation may have failed."

    - name: Ensure `/gbdb/` is a directory
      # "Work around `GBDBDIR` setting being ignored by the installation script" should have been skipped
      block:
        - name: Stat `/gbdb/` directory
          ansible.builtin.stat:
            path: /gbdb/
          register: gbdb_dir_stat

        - name: Assert that `/gbdb/` exists and is a directory
          ansible.builtin.assert:
            that:
              - gbdb_dir_stat.stat.exists
              - gbdb_dir_stat.stat.isdir
            fail_msg: "`/gbdb/` is not a directory. It should be a directory."

    - name: Ensure hg.conf settings have been applied
      block:
        - name: Read hg.conf file
          ansible.builtin.slurp:
            src: "{{ ucsc_genome_browser_setting_CGIBINDIR }}/hg.conf"
          register: hg_conf_slurp

        - name: Decode hg.conf content
          ansible.builtin.set_fact:
            hg_conf_decoded: "{{ hg_conf_slurp.content | b64decode }}"

        - name: Assert hg.conf settings
          ansible.builtin.assert:
            that: "hg_conf_decoded is search('^{{ item.key }}={{ item.value }}$', multiline=True)"
            fail_msg: "One or more hg.conf settings are missing or incorrect."
          loop: "{{ ucsc_genome_browser_hg_conf_settings | dict2items }}"

    - name: Ensure trash cleanup is set up
      block:
        - name: Stat the installed setup script
          ansible.builtin.stat:
            path: "{{ ucsc_genome_browser_setup_script_path }}"
          register: setup_script_stat

        - name: Assert the setup script is installed
          ansible.builtin.assert:
            that: setup_script_stat.stat.exists
            fail_msg: "The setup script was not installed to {{ ucsc_genome_browser_setup_script_path }}."

        - name: Get trash cleanup timer state
          ansible.builtin.systemd_service:
            name: ucsc-genome-browser-clean.timer
          register: clean_timer

        - name: Assert the trash cleanup timer is enabled and running
          ansible.builtin.assert:
            that:
              - clean_timer.status.UnitFileState == "enabled"
              - clean_timer.status.ActiveState == "active"
            fail_msg: "The trash cleanup timer is not enabled and active."
